name: ci

on:
  push:
    branches:
      - "master"
      - "ldap-ng-dev"
  schedule:
      - cron: "0 2 * * 0"

jobs:
  docker:
    runs-on: ubuntu-latest
    environment:
        name: prod
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      -
        name: Build and push event-dispatcher
        uses: docker/build-push-action@v3
        with:
          context: ./server/
          platforms: linux/amd64
          push: true
          tags: "${{ secrets.REGISTRY }}/atlantishq/event-dispatcher:latest"
      -
        name: Build and push event-dispatcher
        uses: docker/build-push-action@v3
        with:
          context: ./client/
          platforms: linux/amd64
          push: true
          tags: "${{ secrets.REGISTRY }}/atlantishq/event-dispatcher-worker:latest"
